import type { CurrencyCode, PlayerDetail } from "../../types/player";
import {
    convertFromGbp,
    formatBonusType,
    formatContractType,
    formatDate,
    formatMoney,
    formatWagePeriod,
} from "../../utils/formatters";

interface ContractPanelProps {
    player: PlayerDetail;
    selectedCurrency: CurrencyCode;
    selectedRate: number;
    onClose: () => void;
}

function ContractPanel({
    player,
    selectedCurrency,
    selectedRate,
    onClose,
}: ContractPanelProps) {
    const contract = player.contract;

    if (!contract) {
        return (
            <div className="modal-backdrop">
                <section className="contract-modal">
                    <div className="modal-header">
                        <h3>Contract</h3>
                        <button onClick={onClose}>×</button>
                    </div>
                    <p>No contract data available.</p>
                </section>
            </div>
        );
    }

    function convertMoney(amount: number | null, currency: CurrencyCode) {
        if (amount === null) return null;

        if (currency === "GBP") {
            return convertFromGbp(amount, selectedRate);
        }

        return amount;
    }

    const wageAmount = convertMoney(contract.wageAmount, contract.wageCurrency);
    const releaseClauseAmount =
        contract.releaseClauseAmount !== null
            ? convertMoney(contract.releaseClauseAmount, contract.releaseClauseCurrency ?? "GBP")
            : null;

    return (
        <div className="modal-backdrop">
            <section className="contract-modal">
                <div className="modal-header">
                    <h3>Contract</h3>
                    <button onClick={onClose}>×</button>
                </div>

                <div className="contract-grid">
                    <div>
                        <span>Type</span>
                        <strong>{formatContractType(contract.contractType)}</strong>
                    </div>

                    <div>
                        <span>Dates</span>
                        <strong>
                            {formatDate(contract.startDate)} - {formatDate(contract.endDate)}
                        </strong>
                    </div>

                    <div>
                        <span>Wage</span>
                        <strong>
                            {formatMoney(wageAmount, selectedCurrency)}{" "}
                            {formatWagePeriod(contract.wageDisplayPeriod)}
                        </strong>
                    </div>

                    <div>
                        <span>Squad Number</span>
                        <strong>{contract.squadNumber ?? "N/A"}</strong>
                    </div>

                    <div>
                        <span>Team Status</span>
                        <strong>{contract.teamName}</strong>
                    </div>

                    <div>
                        <span>Release Clause</span>
                        <strong>
                            {releaseClauseAmount
                                ? formatMoney(releaseClauseAmount, selectedCurrency)
                                : "None"}
                        </strong>
                    </div>
                </div>

                <div className="bonus-list">
                    <h4>Contract Bonuses</h4>

                    {contract.bonuses.map((bonus) => {
                        const convertedBonus =
                            bonus.currency === "GBP"
                                ? convertFromGbp(bonus.amount, selectedRate)
                                : bonus.amount;

                        return (
                            <div key={bonus.bonusType} className="bonus-row">
                                <span>
                                    {formatBonusType(bonus.bonusType)}
                                    {bonus.autoGenerated && <small> Auto</small>}
                                </span>
                                <strong>{formatMoney(convertedBonus, selectedCurrency)}</strong>
                            </div>
                        );
                    })}
                </div>
            </section>
        </div>
    );
}

export default ContractPanel;