package com.clubops.finance;

import com.clubops.club.Club;
import com.clubops.club.ClubRepository;
import com.clubops.contract.ContractBonus;
import com.clubops.contract.ContractBonusRepository;
import com.clubops.contract.PlayerContract;
import com.clubops.contract.PlayerContractRepository;
import com.clubops.currency.CurrencyCode;
import com.clubops.finance.dto.FinanceSummaryResponse;
import com.clubops.user.User;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.List;

@Service
@RequiredArgsConstructor
public class FinanceService {

    private static final BigDecimal WEEKS_PER_YEAR = BigDecimal.valueOf(52);
    private static final BigDecimal MONTHS_PER_YEAR = BigDecimal.valueOf(12);

    private final ClubRepository clubRepository;
    private final PlayerContractRepository playerContractRepository;
    private final ContractBonusRepository contractBonusRepository;

    public FinanceSummaryResponse getCurrentUserFinance(User user) {
        Club club = clubRepository.findByUser(user)
                .orElseThrow(() -> new RuntimeException("Club not found"));

        List<PlayerContract> contracts = playerContractRepository
                .findByClubOrderByTeamDisplayOrderAscPlayerDisplayNameAsc(club);

        BigDecimal weeklyBaseWage = BigDecimal.ZERO;
        BigDecimal weeklyAutoBonuses = BigDecimal.ZERO;
        BigDecimal weeklyAllBonuses = BigDecimal.ZERO;

        for (PlayerContract contract : contracts) {
            requireGbp(contract);
            weeklyBaseWage = weeklyBaseWage.add(toWeeklyWage(contract));

            List<ContractBonus> bonuses = contractBonusRepository
                    .findByContractOrderByBonusTypeAsc(contract);

            for (ContractBonus bonus : bonuses) {
                if (bonus.getCurrency() != CurrencyCode.GBP) {
                    throw new IllegalArgumentException(
                            "Finance summary currently supports GBP bonuses only"
                    );
                }

                if (Boolean.TRUE.equals(bonus.getAutoGenerated())) {
                    weeklyAutoBonuses = weeklyAutoBonuses.add(bonus.getAmount());
                }

                weeklyAllBonuses = weeklyAllBonuses.add(bonus.getAmount());
            }
        }

        BigDecimal weeklyMaxCost = weeklyBaseWage.add(weeklyAllBonuses);

        return new FinanceSummaryResponse(
                CurrencyCode.GBP,
                weeklyBaseWage,
                toMonthly(weeklyBaseWage),
                weeklyBaseWage.multiply(WEEKS_PER_YEAR),
                weeklyAutoBonuses,
                toMonthly(weeklyAutoBonuses),
                weeklyAutoBonuses.multiply(WEEKS_PER_YEAR),
                weeklyMaxCost,
                toMonthly(weeklyMaxCost),
                weeklyMaxCost.multiply(WEEKS_PER_YEAR),
                contracts.size()
        );
    }

    private void requireGbp(PlayerContract contract) {
        if (contract.getWageCurrency() != CurrencyCode.GBP) {
            throw new IllegalArgumentException(
                    "Finance summary currently supports GBP contracts only"
            );
        }
    }

    private BigDecimal toWeeklyWage(PlayerContract contract) {
        BigDecimal amount = contract.getWageAmount();

        return switch (contract.getWageDisplayPeriod()) {
            case WEEKLY -> amount;
            case MONTHLY -> amount.multiply(MONTHS_PER_YEAR)
                    .divide(WEEKS_PER_YEAR, 2, RoundingMode.HALF_UP);
            case YEARLY -> amount.divide(WEEKS_PER_YEAR, 2, RoundingMode.HALF_UP);
        };
    }

    private BigDecimal toMonthly(BigDecimal weeklyAmount) {
        return weeklyAmount.multiply(WEEKS_PER_YEAR)
                .divide(MONTHS_PER_YEAR, 2, RoundingMode.HALF_UP);
    }
}
