import type { TeamType } from "./club";

export type CountryCode =
    | "ENGLAND"
    | "SCOTLAND"
    | "WALES"
    | "NORTHERN_IRELAND"
    | "IRELAND"
    | "FRANCE"
    | "SPAIN"
    | "GERMANY"
    | "ITALY"
    | "PORTUGAL"
    | "NETHERLANDS"
    | "BELGIUM"
    | "TURKEY"
    | "SAUDI_ARABIA"
    | "BRAZIL"
    | "ARGENTINA"
    | "USA"
    | "CANADA"
    | "MEXICO"
    | "JAPAN"
    | "SOUTH_KOREA"
    | "CHINA"
    | "NIGERIA"
    | "GHANA"
    | "SENEGAL"
    | "MOROCCO"
    | "OTHER";

export type CurrencyCode =
    | "GBP"
    | "EUR"
    | "TRY"
    | "SAR"
    | "CNY"
    | "USD"
    | "BRL"
    | "ARS";

export type LanguageCode =
    | "ENGLISH"
    | "SPANISH"
    | "FRENCH"
    | "GERMAN"
    | "ITALIAN"
    | "PORTUGUESE"
    | "DUTCH"
    | "TURKISH"
    | "ARABIC"
    | "JAPANESE"
    | "KOREAN"
    | "CHINESE"
    | "OTHER";

export type PlayerPositionType =
    | "GOALKEEPER"
    | "DEFENDER_LEFT"
    | "DEFENDER_CENTRAL"
    | "DEFENDER_RIGHT"
    | "DEFENSIVE_MIDFIELDER"
    | "WING_BACK_LEFT"
    | "WING_BACK_RIGHT"
    | "MIDFIELDER_LEFT"
    | "MIDFIELDER_CENTRAL"
    | "MIDFIELDER_RIGHT"
    | "ATTACKING_MIDFIELDER_LEFT"
    | "ATTACKING_MIDFIELDER_CENTRAL"
    | "ATTACKING_MIDFIELDER_RIGHT"
    | "STRIKER";

export type ContractBonusType =
    | "APPEARANCE_FEE"
    | "GOAL_BONUS"
    | "ASSIST_BONUS"
    | "CLEAN_SHEET_BONUS"
    | "INTERNATIONAL_CAP_BONUS"
    | "UNUSED_SUBSTITUTE_FEE";

export type PlayerContractType =
    | "FULL_TIME"
    | "PART_TIME"
    | "AMATEUR"
    | "YOUTH";

export type WageDisplayPeriod = "WEEKLY" | "MONTHLY" | "YEARLY";

export type ReleaseClauseRule = "REQUIRED" | "OPTIONAL" | "FORBIDDEN";

export interface ReleaseClausePolicy {
    rule: ReleaseClauseRule;
}

export interface PlayerListItem {
    id: number;
    displayName: string;
    fullName: string;
    age: number;
    nationality: CountryCode;
    teamId: number;
    teamName: string;
    currentAbility: number;
    potentialAbility: number;
    isGoalkeeper: boolean;
    estimatedValueInGbp: number | null;
    weeklyWage: number | null;
    wageCurrency: CurrencyCode | null;
}

export interface PlayerPosition {
    id: number;
    positionType: PlayerPositionType;
    rating: number;
}

export interface PlayerLanguage {
    languageCode: LanguageCode;
    fluency: number;
}

export interface PlayerSecondaryNationality {
    countryCode: CountryCode;
}

export interface CurrencyInfo {
    code: CurrencyCode;
    name: string;
    symbol: string;
    rateFromGbp: number;
}

export interface ContractBonus {
    bonusType: ContractBonusType;
    amount: number;
    currency: CurrencyCode;
    autoGenerated: boolean;
}

export interface PlayerContract {
    id: number;
    startDate: string;
    endDate: string;
    contractType: PlayerContractType;
    wageAmount: number;
    wageCurrency: CurrencyCode;
    wageDisplayPeriod: WageDisplayPeriod;
    teamId: number;
    teamName: string;
    teamType: TeamType;
    squadNumber: number | null;
    releaseClauseAmount: number | null;
    releaseClauseCurrency: CurrencyCode | null;
    bonuses: ContractBonus[];
}

export interface ContractListItem {
    playerId: number;
    playerName: string;
    teamName: string;
    squadNumber: number | null;
    startDate: string;
    endDate: string;
    contractType: PlayerContractType;
    wageAmount: number;
    wageCurrency: CurrencyCode;
    wageDisplayPeriod: WageDisplayPeriod;
    releaseClauseAmount: number | null;
    releaseClauseCurrency: CurrencyCode | null;
}

export interface FinanceSummary {
    baseCurrency: CurrencyCode;
    weeklyBaseWage: number;
    monthlyBaseWage: number;
    yearlyBaseWage: number;
    weeklyAutoBonusCost: number;
    monthlyAutoBonusCost: number;
    yearlyAutoBonusCost: number;
    weeklyMaxCost: number;
    monthlyMaxCost: number;
    yearlyMaxCost: number;
    playerCount: number;
}

export interface PlayerValue {
    estimatedValueInGbp: number | null;
    baseCurrency: CurrencyCode;
    calculated: boolean;
}

export interface PlayerAttributeGroups {
    ability: Record<string, number>;
    reputation: Record<string, number>;
    feet: Record<string, number>;
    personal: Record<string, number>;
    mental: Record<string, number>;
    physical: Record<string, number>;
    technical: Record<string, number>;
    goalkeeping: Record<string, number>;
}

export interface PlayerDetail {
    id: number;

    firstName: string;
    lastName: string;
    commonName: string | null;
    fullName: string;
    displayName: string;

    age: number;
    dateOfBirth: string;

    race: string;
    hairColor: string;
    hairLength: string;
    skinTone: string;

    heightCm: number;
    weightKg: number;

    birthCity: string;
    birthCountry: CountryCode;
    nationality: CountryCode;
    secondaryNationalities: PlayerSecondaryNationality[];
    languages: PlayerLanguage[];

    clubId: number;
    clubName: string;
    teamId: number;
    teamName: string;
    teamType: TeamType;

    isGoalkeeper: boolean;

    positions: PlayerPosition[];
    attributes: PlayerAttributeGroups;

    personality: string;
    mediaHandlingStyle: string;

    contract: PlayerContract | null;
    value: PlayerValue | null;
    defaultCurrency: CurrencyCode;
    availableCurrencies: CurrencyInfo[];
}
