package com.clubops.contract.dto;

import com.clubops.contract.ContractBonus;
import com.clubops.contract.ContractBonusType;
import com.clubops.currency.CurrencyCode;

import java.math.BigDecimal;

public record ContractBonusResponse(
        ContractBonusType bonusType,
        BigDecimal amount,
        CurrencyCode currency,
        Boolean autoGenerated
) {
    public static ContractBonusResponse from(ContractBonus bonus) {
        return new ContractBonusResponse(
                bonus.getBonusType(),
                bonus.getAmount(),
                bonus.getCurrency(),
                bonus.getAutoGenerated()
        );
    }
}