package com.clubops.finance;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.when;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import com.clubops.club.Club;
import com.clubops.club.ClubRepository;
import com.clubops.contract.ContractBonus;
import com.clubops.contract.ContractBonusRepository;
import com.clubops.contract.PlayerContract;
import com.clubops.contract.PlayerContractRepository;
import com.clubops.contract.WageDisplayPeriod;
import com.clubops.currency.CurrencyCode;
import com.clubops.finance.dto.FinanceSummaryResponse;
import com.clubops.user.User;

@ExtendWith(MockitoExtension.class)
class FinanceServiceTests {

    @Mock
    private ClubRepository clubRepository;
    @Mock
    private PlayerContractRepository playerContractRepository;
    @Mock
    private ContractBonusRepository contractBonusRepository;

    @InjectMocks
    private FinanceService financeService;

    @Test
    void financeSummaryNormalizesWagePeriodsAndTotalsBonuses() {
        User user = new User();
        Club club = new Club();
        PlayerContract weeklyContract = contract("1000", WageDisplayPeriod.WEEKLY);
        PlayerContract monthlyContract = contract("4333.33", WageDisplayPeriod.MONTHLY);
        ContractBonus autoBonus = bonus("200", true);
        ContractBonus optionalBonus = bonus("300", false);

        when(clubRepository.findByUser(user)).thenReturn(Optional.of(club));
        when(playerContractRepository
                .findByClubOrderByTeamDisplayOrderAscPlayerDisplayNameAsc(club))
                .thenReturn(List.of(weeklyContract, monthlyContract));
        when(contractBonusRepository
                .findByContractOrderByBonusTypeAsc(weeklyContract))
                .thenReturn(List.of(autoBonus, optionalBonus));
        when(contractBonusRepository
                .findByContractOrderByBonusTypeAsc(monthlyContract))
                .thenReturn(List.of());

        FinanceSummaryResponse summary =
                financeService.getCurrentUserFinance(user);

        assertThat(summary.weeklyBaseWage()).isEqualByComparingTo("2000.00");
        assertThat(summary.monthlyBaseWage()).isEqualByComparingTo("8666.67");
        assertThat(summary.yearlyBaseWage()).isEqualByComparingTo("104000.00");
        assertThat(summary.weeklyAutoBonusCost()).isEqualByComparingTo("200");
        assertThat(summary.weeklyMaxCost()).isEqualByComparingTo("2500.00");
        assertThat(summary.playerCount()).isEqualTo(2);
    }

    private PlayerContract contract(String amount, WageDisplayPeriod period) {
        return PlayerContract.builder()
                .wageAmount(new BigDecimal(amount))
                .wageCurrency(CurrencyCode.GBP)
                .wageDisplayPeriod(period)
                .build();
    }

    private ContractBonus bonus(String amount, boolean autoGenerated) {
        return ContractBonus.builder()
                .amount(new BigDecimal(amount))
                .currency(CurrencyCode.GBP)
                .autoGenerated(autoGenerated)
                .build();
    }
}
