package com.clubops.player;

public enum PlayerPositionType {
    GOALKEEPER,
    DEFENDER_LEFT,
    DEFENDER_CENTRAL,
    DEFENDER_RIGHT,
    DEFENSIVE_MIDFIELDER,
    WING_BACK_LEFT,
    WING_BACK_RIGHT,
    MIDFIELDER_LEFT,
    MIDFIELDER_CENTRAL,
    MIDFIELDER_RIGHT,
    ATTACKING_MIDFIELDER_LEFT,
    ATTACKING_MIDFIELDER_CENTRAL,
    ATTACKING_MIDFIELDER_RIGHT,
    STRIKER
}