package com.clubops.player;

public enum Race {
    UNKNOWN,
    NORTHERN_EUROPEAN,
    MEDITERRANEAN_HISPANIC,
    NORTH_AFRICAN_MIDDLE_EASTERN,
    AFRICAN_CARIBBEAN,
    ASIAN,
    SOUTH_EAST_ASIAN,
    PACIFIC_ISLANDER,
    NATIVE_AMERICAN,
    NATIVE_AUSTRALIAN,
    MIXED_RACE,
    EAST_ASIAN
}
